services:
  - type: static
    name: pomo-rpg-mockup
    buildCommand: ""
    staticPublishPath: "."
    headers:
      - path: /*
        name: Cache-Control
        value: "no-cache, no-store, must-revalidate"
      - path: /*
        name: Pragma
        value: "no-cache"
      - path: /*
        name: Expires
        value: "0"

